version: "3.7"
networks:
  appnet:
services:
  app-service:
    build: .
    restart: always
    ports:
      - "8081:9991"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-service:3306/mydb
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: sa
    depends_on:
      - db-service
    networks:
      - appnet
  db-service:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: sa
      MYSQL_PASSWORD: sa
      MYSQL_DATABASE: mydb
    networks:
      - appnet